spring:
  main:
    banner-mode: off
    keep-alive: true
    log-startup-info: false
    lazy-initialization: true
  threads:
    virtual:
      enabled: true
  ssl:
    bundle:
      pem:
        https:
          reload-on-update: true
          keystore:
            verify-keys: true
            certificate: ${MY_CERTIFICATE_PATH}
            private-key: ${MY_CERTIFICATE_KEY_PATH}
            private-key-password: ${MY_CERTIFICATE_KEY_PASSWORD:}
  web:
    resources:
      add-mappings: false
  datasource:
    url: "jdbc:postgresql://${MY_DB_HOST}:${MY_DB_PORT:5432}/${MY_DB_NAME}"
    username: ${MY_DB_USERNAME}
    password: ${MY_DB_PASSWORD}
  jpa:
    show-sql: false
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

server:
  address: ${MY_ADDRESS:0.0.0.0}
  port: ${MY_PORT:443}
  shutdown: graceful
  ssl:
    enabled: true
    bundle: https
  http2:
    enabled: true
  compression:
    enabled: true
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
    jsp:
      registered: false
  tomcat:
    uri-encoding: UTF-8
